name: Deploy to GitHub Pages

on:
  push:
    branches:
      - portfolio

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build
      # Configure Git user for gh-pages with secrets
      - name: Configure Git
        run: |
          git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
          git config --global user.name "${{ secrets.GIT_USER_NAME }}"

      - name: Deploy to GitHub Pages
        run: npm install gh-pages --save-dev && npm run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }} # This is automatically created by GitHub Actions
