name: Lint Code

on:
  pull_request:
    branches:
      - portfolio # Run on push to portfolio branch (adjust to your branch name)

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22" # Use the version you want

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run linting
      - name: Run Linting
        run: npm run lint
